# A Docker image to build a container with all the dependencies to build and run AroLib in
FROM ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update &&\
    apt-get install -qq -y \
    bash \
    cmake \
    g++ \
    libboost-dev \
    libboost-system-dev \
    libboost-filesystem-dev \
    libboost-test-dev \
    libgdal-dev \
    libshp-dev \
    libpng++-dev \
    libcrypto++-dev \
    libhdf5-dev \
    && rm -rf /var/lib/apt/lists/*
